[versions] # =======================================================================================
kotlinCompilerExtension = "1.5.9"
googleServices = "4.4.2"
agp = "8.12.0"
kotlin = "2.2.20"
firevaseCrashlyticsPlugin = "3.0.2"
androidMinSdk = "26"
androidCompileSdk = "36"

# Ktor #
ktor = "2.3.10"

# DataStore #
dataStore = "1.1.1"

# Kotlin Serialization #
kotlinSerialization = "1.6.3"
kotlinSerializationPlugin = "1.9.10"

# Work Manager #
workManager = "2.9.0"

# Core #
androidxCore = "1.13.1"
androidxAppCompat = "1.7.0"
androidxLegacySupport = "1.0.0"
coroutinesCoreJvm = "1.7.3"
datetime = "0.7.1"
javaxInject = "1"

# Tests #
junitCore = "4.13.2"
mockkCore = "1.12.4"
espressoCore = "3.4.0"
junitAndroid = "1.1.3"
coroutineTest = "1.6.4"
turbine = "0.10.0"

# Navigation #
navigationCore = "2.9.2"

# Room #
roomCore = "2.8.4"
roomPlugin = "2.8.4"
sqliteBundled = "2.6.2"

# Lifecycle #
lifecycle = "2.9.4"

# Koin #
koin = "4.1.1"

# Moko Permissions #
mokoPermissions = "0.20.1"

# Firebase #
firebaseBom = "33.1.2"
firebaseCoroutinePlayServices = "1.7.3"
firebaseFirestoreKtx = "25.0.0"
firebaseAuthenticationKtx = "23.0.0"
firebaseCrashlyticsKtx = "19.0.3"

# Compose #
composeBom = "2024.06.00"
composeComiler = "1.5.14"
composeMultiplatform = "1.10.1"

# LoKdroid #
lokdroid = "0.0.4-alpha"

# Mosaic #
mosaic = "0.18.0"

# KSP #
ksp = "2.2.20-2.0.4"

# Cambridge Lib #
cambridgeLib = "1.0.0"

# SplashScreen API #
coreSplashscreen = "1.2.0-alpha01"
junitJupiter = "5.8.1"
jetbrainsKotlinJvm = "1.9.22"
material3Android = "1.3.2"
runner = "1.5.2"
core = "1.5.0"

[libraries] # ======================================================================================
# Core #
core-kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
core-android-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
core-app-compat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppCompat" }
core-legacy-support = { group = "androidx.legacy", name = "legacy-support-v4", version.ref = "androidxLegacySupport" }
core-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutinesCoreJvm" }
core-coroutines-core-jvm = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core-jvm", version.ref = "coroutinesCoreJvm" }
core-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "coroutinesCoreJvm" }
core-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "datetime" }
core-javax-inject = { group = "javax.inject", name = "javax.inject", version.ref = "javaxInject" }

# Tests #
tests-junit-core = { group = "junit", name = "junit", version.ref = "junitCore" }
tests-mockk = { group = "io.mockk", name = "mockk", version.ref = "mockkCore" }
tests-espresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
tests-junit-android = { group = "androidx.test.ext", name = "junit", version.ref = "junitAndroid" }
tests-coroutine = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutineTest" }
tests-kotlin = { group = "org.jetbrains.kotlin", name = "kotlin-test" }
tests-turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }

# Navigation
navigation-compose = { group = "org.jetbrains.androidx.navigation", name = "navigation-compose", version.ref = "navigationCore" }

# Room #
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "roomCore" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "roomCore" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "roomCore" }
sqlite-bundled = { group = "androidx.sqlite", name = "sqlite-bundled", version.ref = "sqliteBundled" }

# Lifecycle #
lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "lifecycle" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycle" }
lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime", version.ref = "lifecycle" }
lifecycle-viewmodel-savedstate = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-savedstate", version.ref = "lifecycle" }
lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle" }

# Koin #
koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koin-androidx-workmanager = { group = "io.insert-koin", name = "koin-androidx-workmanager", version.ref = "koin" }
koin-compose = { group = "io.insert-koin", name = "koin-compose", version.ref = "koin" }
koin-compose-viewmodel = { group = "io.insert-koin", name = "koin-compose-viewmodel", version.ref = "koin" }

# Moko Permissions #
moko-permissions = { group = "dev.icerock.moko", name = "permissions", version.ref = "mokoPermissions" }
moko-permissions-notifications = { group = "dev.icerock.moko", name = "permissions-notifications", version.ref = "mokoPermissions" }

# Firebase #
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-coroutine-play-services = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-play-services", version.ref = "firebaseCoroutinePlayServices" }
firebase-analytics-kts = { group = "com.google.firebase", name = "firebase-analytics-ktx" }
firebase-rirestore-ktx = { group = "com.google.firebase", name = "firebase-firestore-ktx", version.ref = "firebaseFirestoreKtx" }
firebase-authentication = { group = "com.google.firebase", name = "firebase-auth-ktx", version.ref = "firebaseAuthenticationKtx" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics-ktx", version.ref = "firebaseCrashlyticsKtx" }

# Compose #
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-compiler = { group = "androidx.compose.compiler", name = "compiler", version.ref = "composeComiler" }
compose-activity = { group = "androidx.activity", name = "activity-compose" }
compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-backhandler = { group = "org.jetbrains.compose.ui", name = "ui-backhandler", version.ref = "composeMultiplatform" }
compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
compose-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-multiplatform-tooling-preview = { group = "org.jetbrains.compose.ui", name = "ui-tooling-preview", version.ref = "composeMultiplatform" }

# Work Manager #
work-manager = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workManager" }

# Kotlin Serialization #
kotlin-serilization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinSerialization" }

# DataStore #
datastore-android = { group = "androidx.datastore", name = "datastore", version.ref = "dataStore" }
datastore-core = { group = "androidx.datastore", name = "datastore-core", version.ref = "dataStore" }
datastore-preferences-core = { group = "androidx.datastore", name = "datastore-preferences-core", version.ref = "dataStore" }
datastore-preferences-android = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "dataStore" }

# Ktor #
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

# LoKdroid #
lokdroid = { group = "io.github.nikolaykuts", name = "lokdroid", version.ref = "lokdroid" }

# Mosaic #
mosaic-runtime = { group = "com.jakewharton.mosaic", name = "mosaic-runtime", version.ref = "mosaic" }

# Cambridge Lib #
cambridge-dictionary-core  = { group = "com.cambridge.dictionary", name = "core", version.ref = "cambridgeLib" }
cambridge-dictionary-client  = { group = "com.cambridge.dictionary", name = "client", version.ref = "cambridgeLib" }

# SplashScreen API #
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }

# plugin dependencies
agp = { group = "com.android.tools.build", name = "gradle", version.ref = "agp"}
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junitJupiter" }
androidx-material3-android = { group = "androidx.compose.material3", name = "material3-android", version.ref = "material3Android" }
androidx-runner = { group = "androidx.test", name = "runner", version.ref = "runner" }
androidx-core = { group = "androidx.test", name = "core", version.ref = "core" }

[bundles]
ktor = ["ktor-client-okhttp", "ktor-client-core", "ktor-client-cio", "ktor-client-content-negotiation", "ktor-serialization-kotlinx-json"]

[plugins] # ========================================================================================
android-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinSerializationPlugin" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firevaseCrashlyticsPlugin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
telegramAppDistribution = { id = "telegram-app-distribution-plugin" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
# Compose
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
# Kmp
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
android-lint = { id = "com.android.lint", version.ref = "agp" }
# Room
room = { id = "androidx.room", version.ref = "roomPlugin" }
