package com.example.klaf.di.dependencies

object Versions {

    const val Kotlin = "1.8.21"
    const val AndroidxCore = "1.9.0"
    const val AndroidxAppCompat = "1.5.1"
    const val AndroidxLegacySupport = "1.0.0"
    const val AndroidxConstraintLayout = "2.1.4"
    const val AndroidxFragmentKtx = "1.5.4"
    const val Material = "1.7.0"
    const val CoroutinesCoreJvm = "1.6.4"
    const val JavaxInject = "1"
    const val Preferences = "1.2.0"
    const val EspressoCore = "3.4.0"
    const val MockkCore = "1.12.4"
    const val CoroutineTest = "1.6.4"
    const val Turbine = "0.10.0"
    const val NavigationCore = "2.4.2"
    const val RoomCore = "2.4.3"
    const val Lifecycle = "2.4.1"
    const val JunitCore = "4.13.2"
    const val JunitAndroid = "1.1.3"
    const val HiltAndroid = "2.44"
    const val HiltDaggerCompiler = "2.44.2"
    const val HiltAndroidCompiler = "1.0.0"
    const val HiltWork = "1.0.0"
    const val FirebaseBom = "31.5.0"
    const val FirebaseCoroutinePlayServices = "1.6.1"
    const val ComposeBom = "2023.06.00"
    const val ComposeCompiler = "1.4.7"
    const val ComposeConstraintLayout = "1.0.1"
    const val ComposeThemeAdapter = "1.2.1"
    const val ComposeAccompanist = "0.19.0"
    const val WorkManagerCore = "2.7.1"
    const val SerializationCore = "1.4.1"
    const val DataStoreCore = "1.0.0"
    const val RetrofitCore = "2.9.0"
}